#!/bin/bash
# VEP Pipeline Email Integration Snippet
# Copy and paste these sections into your comprehensive_vep_v114.sh script

echo "==================================================================="
echo "VEP PIPELINE EMAIL INTEGRATION SNIPPET"
echo "==================================================================="
echo ""
echo "Copy the following sections into your comprehensive_vep_v114.sh:"
echo ""

echo "1. ADD AFTER INITIAL VARIABLES (around line 20-30):"
echo "   # Email notification setup"
echo "   EMAIL_NOTIFIER=\"/mnt/d/Genome/scripts/pipeline_notifier.py\""
echo "   EMAIL_CONFIG=\"/mnt/d/Genome/config/email_config.json\""
echo "   EMAIL_ENABLED=true"
echo ""
echo "   # Function to send email notification"
echo "   send_email_notification() {"
echo "       local notification_type=\"\$1\""
echo "       local sample_id=\"\$2\""
echo "       local start_time=\"\$3\""
echo "       local end_time=\"\$4\""
echo "       local output_file=\"\$5\""
echo "       local file_size=\"\$6\""
echo "       local variant_count=\"\$7\""
echo "       local error_message=\"\$8\""
echo "       "
echo "       if [[ \"\${EMAIL_ENABLED}\" == \"true\" && -f \"\${EMAIL_NOTIFIER}\" ]]; then"
echo "           echo \"[\$(date '+%Y-%m-%d %H:%M:%S')] 📧 Sending \${notification_type} notification...\""
echo "           python3 \"\${EMAIL_NOTIFIER}\" --type \"\${notification_type}\" \\"
echo "               --sample-id \"\${sample_id}\" --start-time \"\${start_time}\" \\"
echo "               --end-time \"\${end_time}\" --output-file \"\${output_file}\" \\"
echo "               --file-size \"\${file_size}\" --variant-count \"\${variant_count}\" \\"
echo "               --error-message \"\${error_message}\" --config \"\${EMAIL_CONFIG}\" || {"
echo "               echo \"[\$(date '+%Y-%m-%d %H:%M:%S')] ⚠️  Email notification failed (non-critical)\""
echo "           }"
echo "       fi"
echo "   }"
echo ""

echo "2. ADD BEFORE VEP EXECUTION (before the big vep command):"
echo "   VEP_START_TIME=\$(date)"
echo ""

echo "3. REPLACE VEP SUCCESS SECTION with this enhanced version:"
echo "   VEP_END_TIME=\$(date)"
echo "   VEP_END_TIMESTAMP=\$(date '+%Y-%m-%d %H:%M:%S')"
echo "   "
echo "   # Calculate duration"
echo "   VEP_DURATION=\$(echo \$(($(date -d \"\${VEP_END_TIME}\" +%s) - $(date -d \"\${VEP_START_TIME}\" +%s))))"
echo "   VEP_DURATION_FORMATTED=\$(printf \"%dm %ds\" \$((VEP_DURATION/60)) \$((VEP_DURATION%60)))"
echo "   "
echo "   echo \"[\${VEP_END_TIMESTAMP}] ✅ SUCCESS: VEP annotation completed in \${VEP_DURATION_FORMATTED}\""
echo "   "
echo "   # Check output file and get metrics"
echo "   if [[ -f \"\${OUTPUT_VCF}\" ]]; then"
echo "       OUTPUT_SIZE=\$(du -h \"\${OUTPUT_VCF}\" | cut -f1)"
echo "       VARIANT_COUNT=\$(zcat \"\${OUTPUT_VCF}\" | grep -v \"^#\" | wc -l)"
echo "       "
echo "       echo \"[\$(date '+%Y-%m-%d %H:%M:%S')] ✅ SUCCESS: Output VCF created: \${OUTPUT_VCF}\""
echo "       echo \"[\$(date '+%Y-%m-%d %H:%M:%S')] ℹ️  INFO: Output size: \${OUTPUT_SIZE}, variants: \${VARIANT_COUNT}\""
echo "       "
echo "       # Send success email notification"
echo "       send_email_notification \"vep_completion\" \"\${SAMPLE_ID}\" \"\${VEP_START_TIME}\" \"\${VEP_END_TIME}\" \\"
echo "                              \"\${OUTPUT_VCF}\" \"\${OUTPUT_SIZE}\" \"\${VARIANT_COUNT}\""
echo "   else"
echo "       # Output file missing - treat as failure"
echo "       ERROR_MSG=\"VEP completed but output file \${OUTPUT_VCF} not found\""
echo "       echo \"[\$(date '+%Y-%m-%d %H:%M:%S')] ❌ ERROR: \${ERROR_MSG}\""
echo "       "
echo "       send_email_notification \"vep_failure\" \"\${SAMPLE_ID}\" \"\${VEP_START_TIME}\" \"\${VEP_END_TIME}\" \\"
echo "                              \"\" \"\" \"0\" \"\${ERROR_MSG}\""
echo "       exit 1"
echo "   fi"
echo ""

echo "4. ADD FOR VEP FAILURES (in your error handling):"
echo "   VEP_END_TIME=\$(date)"
echo "   ERROR_MSG=\"VEP annotation failed. Check log file: \${LOG_FILE}\""
echo "   "
echo "   send_email_notification \"vep_failure\" \"\${SAMPLE_ID}\" \"\${VEP_START_TIME}\" \"\${VEP_END_TIME}\" \\"
echo "                          \"\" \"\" \"0\" \"\${ERROR_MSG}\""
echo ""

echo "==================================================================="
echo "QUICK SETUP COMMANDS:"
echo "==================================================================="
echo ""
echo "1. Make setup script executable and run it:"
echo "   chmod +x /mnt/d/Genome/scripts/setup_email_notifications.sh"
echo "   bash /mnt/d/Genome/scripts/setup_email_notifications.sh"
echo ""
echo "2. Test the email system:"
echo "   python3 /mnt/d/Genome/scripts/pipeline_notifier.py \\"
echo "     --type vep_completion --sample-id TEST_SAMPLE \\"
echo "     --start-time \"\$(date -d '3 hours ago')\" \\"
echo "     --variant-count 1000000 --file-size \"1.2G\" \\"
echo "     --config /mnt/d/Genome/config/email_config.json"
echo ""
echo "3. Integrate with your VEP script using the snippets above"
echo ""
echo "4. Run your pipeline and enjoy email notifications! 📧"
